In [16]:
import pandas as pd

In [17]:
airqualityindex = pd.read_csv("https://data.wprdc.org/datastore/dump/4ab1e23f-3262-4bd3-adbf-f72f0119108b")

In [18]:
airqualityindex

,date,site,parameter,index_value,description,health_advisory,health_effects
0,2016-01-01,Lawrenceville,PM25B,25,Good,NaN,NaN
1,2016-01-01,Flag Plaza,CO,0,Good,NaN,NaN
2,2016-01-01,Harrison Township,OZONE,31,Good,NaN,NaN
3,2016-01-01,Avalon,SO2,10,Good,NaN,NaN
4,2016-01-01,Lincoln,PM25,35,Good,NaN,NaN
...,...,...,...,...,...,...,...
47840,2021-11-14,South Fayette,SO2,0,Good,NaN,NaN
47841,2021-11-14,Pittsburgh,PM25_640,28,Good,NaN,NaN
47842,2021-11-14,Liberty 2,PM25T,23,Good,NaN,NaN
47843,2021-11-14,Parkway East,PM25T,18,Good,NaN,NaN
47844,2021-11-14,Avalon,PM25T,19,Good,NaN,NaN

In [19]:
artdata = pd.read_csv("https://data.wprdc.org/datastore/dump/00d74e83-8a23-486e-841b-286e1332a151")

In [20]:
airqualityindex.groupby('site')['index_value'].mean()

site
Avalon                   20.694054
Clairton                  7.273556
Flag Plaza                9.853728
Glassport High Street    17.267731
Harrison Township        24.363148
Lawrenceville            38.468050
Lawrenceville 2           3.107261
Liberty                  18.781046
Liberty 2                32.353250
Lincoln                  35.108002
North Braddock           17.986943
Parkway East             22.310798
Pittsburgh               29.984424
South Fayette            20.621667
West Mifflin              6.335548
Name: index_value, dtype: float64

In [21]:
artdata

,id,name,title,artist_name,art_type,park,image,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
0,812728309,1001,Oakwood Road Monument,NaN,NaN,NaN,NaN,Oakwood,2.0,28.0,4.200356e+10,5.0,28.0,6.0,1-19,40.429192,-80.066225
1,188255168,1002,Rooster Waiting For The Streetcar,James Simon,Modern and Contemporary Art,NaN,NaN,Elliott,2.0,20.0,4.200356e+10,5.0,20.0,6.0,1-17,40.442926,-80.039711
2,2032091917,129,Middle East Memorial Plaque,NaN,War Memorials,NaN,NaN,Central Business District,6.0,1.0,4.200302e+10,6.0,1.0,2.0,1-4,40.438092,-79.996852
3,1447629273,143,L'Enfant,Paul Roger-Bloche,Historic Art,NaN,NaN,Carrick,4.0,29.0,4.200329e+10,3.0,29.0,3.0,4-23,40.388748,-79.986497
4,1935017944,148,Veterans Memorial (Brookline),NaN,War Memorials,Brookline Monument,NaN,Brookline,4.0,19.0,4.200319e+10,5.0,19.0,6.0,4-26,40.391721,-80.016981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,1089921133,WM00099000,17th Ward Veterans Memorial,NaN,Non-City Owned,NaN,NaN,South Side Flats,3.0,17.0,4.200317e+10,3.0,17.0,3.0,4-24,40.428635,-79.980443
195,191395610,WM00101000,Saint Josephat Honor Roll,NaN,Non-City Owned,NaN,NaN,South Side Slopes,3.0,16.0,4.200316e+10,3.0,16.0,3.0,4-22,40.423129,-79.973486
196,628976107,WM00102000,World War II Momument,NaN,Non-City Owned,NaN,NaN,Spring Garden,1.0,26.0,4.200324e+10,1.0,26.0,1.0,1-11,40.471780,-79.986670
197,1309894649,WM00105000,Korean War Veterans Memorial,R. Allan Christianson (Architect),War Memorials,Northshore Riverfront Park,NaN,North Shore,1.0,22.0,4.200398e+10,6.0,22.0,1.0,1-7,40.445726,-80.008082
198,1903851764,WM00107000,Vietnam Veterans Memorial,George Danhires,War Memorials,Northshore Riverfront Park,NaN,North Shore,1.0,22.0,4.200398e+10,6.0,22.0,1.0,1-7,40.445207,-80.010831

In [22]:
artdata.groupby('neighborhood')['neighborhood'].count()

neighborhood
Allegheny Center             18
Allegheny West                1
Allentown                     2
Beechview                     7
Beltzhoover                   3
Bloomfield                    1
Brighton Heights              5
Brookline                     2
Carrick                       2
Central Business District    27
Central Lawrenceville         2
Central Oakland               5
Crafton Heights               1
Crawford-Roberts              3
Duquesne Heights              3
East Allegheny                2
East Carnegie                 1
East Hills                    1
East Liberty                  1
Elliott                       3
Esplen                        1
Garfield                      2
Greenfield                    3
Hays                          1
Hazelwood                     3
Highland Park                10
Knoxville                     1
Lincoln-Lemington-Belmar      2
Lower Lawrenceville           5
Manchester                    1
Mount Washington              2
North Oakland                 1
North Shore                   8
Oakwood                       1
Overbrook                     1
Perry North                   2
Perry South                   1
Point Breeze                  3
Polish Hill                   1
Regent Square                 1
Shadyside                     6
Sheraden                      1
South Side Flats              9
South Side Slopes             3
Spring Garden                 2
Spring Hill-City View         4
Squirrel Hill North           2
Squirrel Hill South          20
Stanton Heights               1
Strip District                2
Swisshelm Park                1
Troy Hill                     1
Upper Hill                    2
Upper Lawrenceville           1
West End                      2
Name: neighborhood, dtype: int64